a = int(input("Введіть 1 значення "))
b = int(input("Введіть 2 значення "))
c = int(input("Введіть 3 значення "))

print("a + b = ")
print(a + b)
print("a - b = ")
print(a - b)
print("a * b = ")
print(a * b)
print("a : b = ")
print(a / b)
print("a + b + c = ")
print(a + b + c)
print("a - b - c= ")
print(a - b - c)
print("a * b * c = ")
print(a * b * c)
print("a : b : c= ")
print(a / b / c)
print("great numbers")